services:
  meilisearch:
    image: getmeili/meilisearch:v1.53.1
    environment:
      MEILI_ENV: development
    secrets:
      - meili_master_key
    entrypoint:
      - sh
      - -c
      - >-
        export MEILI_MASTER_KEY="$$(cat /run/secrets/meili_master_key)";
        exec /bin/meilisearch
    volumes:
      - meilisearch_data:/meili_data

  teacher_coop:
    image: eguefif/teacher_coop:20260919130041
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHX_HOST: "www.teachercoop.org"
    secrets:
      - database_url
      - secret_key_base
      - meili_master_key
    command:
      - sh
      - -c
      - >-
        export DATABASE_URL="$$(cat /run/secrets/database_url)";
        export SECRET_KEY_BASE="$$(cat /run/secrets/secret_key_base)";
        export MEILISEARCH_MASTERKEY="$$(cat /run/secrets/meili_master_key)";
        exec /app/bin/server
    volumes:
      - ./:/app/data
    depends_on:
      - meilisearch
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.teacher_coop.rule=Host(`www.teachercoop.org`)"
        - "traefik.http.routers.teacher_coop.entrypoints=web"
        - "traefik.http.services.teacher_coop.loadbalancer.server.port=4000"

  traefik:
    image: traefik:v3.7
    command:
      - "--api.insecure=false"
      - "--api.dashboard=true"
      - "--providers.swarm=true"
      - "--providers.swarm.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      labels:
        - "traefik.http.routers.dashboard.rule=Host(`traefik.teachercoop.org`)"
        - "traefik.http.routers.dashboard.service=api@internal"
        - "traefik.http.routers.dashboard.entrypoints=websecure"
      placement:
        constraints:
          - node.role == manager

volumes:
  meilisearch_data:

secrets:
  database_url:
    external: true
  secret_key_base:
    external: true
  meili_master_key:
    external: true
